name: beacon_broadcast
description: A Flutter plugin for turning your device into a beacon. Plugin uses AltBeacon library for Android and CoreLocation for iOS.
version: 0.3.2
homepage: https://github.com/rtorrecilhas/beacon_broadcast
repository: https://github.com/rtorrecilhas/beacon_broadcast
issue_tracker: https://github.com/rtorrecilhas/beacon_broadcast/issues
license: MIT

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.26.0

flutter:
  plugin:
    platforms:
      android:
        package: pl.pszklarska.beaconbroadcast
        pluginClass: BeaconBroadcastPlugin
      ios:
        pluginClass: BeaconBroadcastPlugin